{
 "title": "Database Exporter",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage (s)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"$job\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "process_open_fds{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OS Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "go_threads{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (MB)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$job\"} / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Внутренняя активность",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PostgreSQL Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC Pause Duration (sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(go_gc_duration_seconds_sum[5m]) / rate(go_gc_duration_seconds_count[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network IO (bytes/sec)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_network_receive_bytes_total{job=\"$job\"}[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(process_network_transmit_bytes_total[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Scrapes",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(pg_exporter_scrapes_total{job=\"$job\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exporter Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "pg_exporter_last_scrape_duration_seconds{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}